Repository YAPP-Github/20th-Web-Team-1-BE, pull requests merged in 2022-06, with the labels that each got.

#4 feat: application.yml파일 설정
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ⚙️Infra

#6 feat: DB 기본 엔티티 생성
  src/main/java/com/yapp/betree/BeTreeApplication.java
  src/main/java/com/yapp/betree/config/swagger/SwaggerConfig.java
  src/main/java/com/yapp/betree/domain/BaseTimeEntity.java
  src/main/java/com/yapp/betree/domain/Folder.java
  src/main/java/com/yapp/betree/domain/FruitType.java
  src/main/java/com/yapp/betree/domain/Message.java
  src/main/java/com/yapp/betree/domain/User.java
Labels: 💡feature

#8 레파지토리, 기본 데이터 생성
  src/main/java/com/yapp/betree/domain/FruitType.java
  src/main/java/com/yapp/betree/repository/FolderRepository.java
  src/main/java/com/yapp/betree/repository/MessageRepository.java
  src/main/java/com/yapp/betree/repository/UserRepository.java
  src/test/java/com/yapp/betree/domain/EntityTest.java
Labels: 📬메시지함, 🔍test

#10 나무, 나무숲 API 기본 설계
  src/main/java/com/yapp/betree/config/swagger/SwaggerConfig.java
  src/main/java/com/yapp/betree/controller/ForestController.java
  src/main/java/com/yapp/betree/dto/response/ForestResponseDto.java
  src/main/java/com/yapp/betree/dto/response/MessageResponseDto.java
  src/main/java/com/yapp/betree/dto/response/TreeFullResponseDto.java
  src/main/java/com/yapp/betree/dto/response/TreeResponseDto.java
  src/main/java/com/yapp/betree/service/FolderService.java
Labels: 📚docs, 💡feature, 🌲칭찬

#11 알림 나무 API 설계
  src/main/java/com/yapp/betree/controller/NoticeTreeController.java
  src/main/java/com/yapp/betree/dto/response/MessageResponseDto.java
  src/main/java/com/yapp/betree/dto/response/NoticeResponseDto.java
  src/main/java/com/yapp/betree/service/NoticeTreeService.java
Labels: 💡feature

#13 feat: 칭찬 메세지 생성 (물 주기) API 설계 #12
  src/main/java/com/yapp/betree/controller/MessageController.java
  src/main/java/com/yapp/betree/controller/NoticeTreeController.java
  src/main/java/com/yapp/betree/domain/Message.java
  src/main/java/com/yapp/betree/dto/request/MessageRequestDto.java
  src/main/java/com/yapp/betree/dto/response/MessageBoxResponseDto.java
  src/main/java/com/yapp/betree/dto/response/MessagePageResponseDto.java
  src/main/java/com/yapp/betree/repository/MessageRepository.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/test/java/com/yapp/betree/controller/MessageControllerTest.java
Labels: 💡feature, 🌲칭찬

#22 feat: 나무, 나무숲, 물주기 추가작업
  src/main/java/com/yapp/betree/controller/ForestController.java
  src/main/java/com/yapp/betree/controller/MessageController.java
  src/main/java/com/yapp/betree/domain/Folder.java
  src/main/java/com/yapp/betree/domain/FruitType.java
  src/main/java/com/yapp/betree/dto/request/MessageRequestDto.java
  src/main/java/com/yapp/betree/dto/request/TreeRequestDto.java
  src/main/java/com/yapp/betree/dto/response/ForestResponseDto.java
  src/main/java/com/yapp/betree/exception/ErrorCode.java
  src/main/java/com/yapp/betree/repository/FolderRepository.java
  src/main/java/com/yapp/betree/service/FolderService.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/test/java/com/yapp/betree/service/FolderServiceTest.java
Labels: 💡feature, 🌲칭찬, 📬메시지함, 🔍test, 🧹refactor

#23 refactor: nickName -> nickname으로 수정
  src/main/java/com/yapp/betree/domain/User.java
  src/main/java/com/yapp/betree/dto/LoginUserDto.java
  src/main/java/com/yapp/betree/dto/response/MessageBoxResponseDto.java
  src/main/java/com/yapp/betree/service/FolderService.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/interceptor/ArgumentResolverTest.java
  src/test/java/com/yapp/betree/repository/UserRepositoryTest.java
  src/test/java/com/yapp/betree/service/JwtTokenTest.java
Labels: 🧹refactor

#25 refactor: 나무, 나무숲 API 추가작업 및 테스트
  src/main/java/com/yapp/betree/controller/ForestController.java
  src/main/java/com/yapp/betree/domain/Folder.java
  src/main/java/com/yapp/betree/dto/oauth/OAuthUserInfoDto.java
  src/main/java/com/yapp/betree/dto/request/TreeRequestDto.java
  src/main/java/com/yapp/betree/dto/response/MessageResponseDto.java
  src/main/java/com/yapp/betree/dto/response/TreeResponseDto.java
  src/main/java/com/yapp/betree/exception/ErrorCode.java
  src/main/java/com/yapp/betree/repository/FolderRepository.java
  src/main/java/com/yapp/betree/service/FolderService.java
  src/main/java/com/yapp/betree/service/UserService.java
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/controller/ForestControllerTest.java
  src/test/java/com/yapp/betree/domain/EntityTest.java
  src/test/java/com/yapp/betree/domain/FolderTest.java
  src/test/java/com/yapp/betree/domain/MessageTest.java
  src/test/java/com/yapp/betree/domain/UserTest.java
  src/test/java/com/yapp/betree/service/FolderServiceTest.java
  src/test/java/com/yapp/betree/service/UserServiceTest.java
Labels: 💡feature, 🌲칭찬, 🔍test, 🧹refactor

#27 [WIP] 물주기, 메세지함 API 작업
  src/main/java/com/yapp/betree/controller/MessageController.java
  src/main/java/com/yapp/betree/domain/Message.java
  src/main/java/com/yapp/betree/dto/request/MessageRequestDto.java
  src/main/java/com/yapp/betree/exception/ErrorCode.java
  src/main/java/com/yapp/betree/repository/FolderRepository.java
  src/main/java/com/yapp/betree/repository/MessageRepository.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/test/java/com/yapp/betree/controller/MessageControllerTest.java
  src/test/java/com/yapp/betree/service/MessageServiceTest.java
Labels: 💡feature, 🌲칭찬, 🔍test, 🧹refactor

#28 [WIP] feat: 알림나무 API
  src/main/java/com/yapp/betree/controller/NoticeTreeController.java
  src/main/java/com/yapp/betree/domain/NoticeTree.java
  src/main/java/com/yapp/betree/dto/response/MessageBoxResponseDto.java
  src/main/java/com/yapp/betree/repository/MessageRepository.java
  src/main/java/com/yapp/betree/repository/NoticeTreeRepository.java
  src/main/java/com/yapp/betree/service/NoticeTreeService.java
  src/main/java/com/yapp/betree/util/BetreeUtils.java
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/util/BetreeUtilsTest.java
Labels: 💡feature, 📌TBD, 🌲칭찬

#32 docs: 리드미 수정 #31
  README.md
Labels: 📚docs

#38 fix: 로그인/비로그인 유저 처리
  src/main/java/com/yapp/betree/controller/ForestController.java
  src/main/java/com/yapp/betree/controller/MessageController.java
  src/main/java/com/yapp/betree/dto/SendUserDto.java
  src/main/java/com/yapp/betree/dto/response/MessageBoxResponseDto.java
  src/main/java/com/yapp/betree/dto/response/MessageResponseDto.java
  src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
  src/main/java/com/yapp/betree/service/FolderService.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/main/java/com/yapp/betree/service/NoticeTreeService.java
  src/main/java/com/yapp/betree/service/UserService.java
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/controller/ForestControllerTest.java
  src/test/java/com/yapp/betree/controller/MessageAcceptanceTest.java
  src/test/java/com/yapp/betree/repository/FolderRepositoryTest.java
  src/test/java/com/yapp/betree/service/FolderServiceTest.java
Labels: 💡feature, 👥회원관리, 🌲칭찬

#34 refactor: 물주기, 메세지함 API 작업
  src/main/java/com/yapp/betree/controller/MessageController.java
  src/main/java/com/yapp/betree/domain/Message.java
  src/main/java/com/yapp/betree/dto/response/MessagePageResponseDto.java
  src/main/java/com/yapp/betree/repository/MessageRepository.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/test/java/com/yapp/betree/controller/MessageControllerTest.java
  src/test/java/com/yapp/betree/service/MessageServiceTest.java
Labels: 🌲칭찬, 🔍test, 🧹refactor
