Repository YAPP-Github/20th-Web-Team-1-BE, pull requests merged in 2022-07, with the labels that each got.

#41 fix: 메세지 dto에 작성일자/시간 추가
  src/main/java/com/yapp/betree/dto/response/MessageBoxResponseDto.java
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/controller/MessageAcceptanceTest.java
  src/test/java/com/yapp/betree/controller/MessageControllerTest.java
  src/test/java/com/yapp/betree/domain/UserTest.java
  src/test/java/com/yapp/betree/service/MessageServiceTest.java
Labels: 💡feature, 📬메시지함, 🧹refactor

#42 fix: 나무(폴더) 최대 생성 개수 4개 제한처리
  src/main/java/com/yapp/betree/controller/ForestController.java
  src/main/java/com/yapp/betree/exception/ErrorCode.java
  src/main/java/com/yapp/betree/repository/FolderRepository.java
  src/main/java/com/yapp/betree/service/FolderService.java
  src/test/java/com/yapp/betree/service/FolderServiceTest.java
Labels: 💡feature, 📬메시지함, 🧹refactor

#46 test: folderRepository 테스트
  src/test/java/com/yapp/betree/repository/folderRepositoryTest.java
Labels: 🔍test

#48 fix: 프론트엔드 건의사항 반영 #47
  src/main/java/com/yapp/betree/controller/ForestController.java
  src/main/java/com/yapp/betree/dto/request/MessageRequestDto.java
  src/main/java/com/yapp/betree/dto/response/TreeResponseDto.java
  src/test/java/com/yapp/betree/controller/ForestControllerTest.java
  src/test/java/com/yapp/betree/domain/FolderTest.java
  src/test/java/com/yapp/betree/repository/folderRepositoryTest.java
Labels: 💡feature, 🌲칭찬

#59 bug: CORS에러 수정
  src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
Labels: ⚒bug

#51 [fix] 발신자, 수신자에 따른 개별 삭제 처리
  src/main/java/com/yapp/betree/domain/Message.java
  src/main/java/com/yapp/betree/repository/MessageRepository.java
  src/main/java/com/yapp/betree/service/FolderService.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/main/java/com/yapp/betree/service/NoticeTreeService.java
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/controller/MessageAcceptanceTest.java
  src/test/java/com/yapp/betree/repository/MessageRepositoryTest.java
  src/test/java/com/yapp/betree/repository/folderRepositoryTest.java
  src/test/java/com/yapp/betree/service/FolderServiceTest.java
  src/test/java/com/yapp/betree/service/MessageServiceTest.java
Labels: 📬메시지함, 🔍test, 🧹refactor

#53 [feat] 유저 조회 및 닉네임 변경 API
  src/main/java/com/yapp/betree/controller/UserController.java
  src/main/java/com/yapp/betree/domain/User.java
  src/main/java/com/yapp/betree/dto/response/UserResponseDto.java
  src/main/java/com/yapp/betree/service/UserService.java
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/controller/UserAcceptanceTest.java
  src/test/java/com/yapp/betree/controller/UserControllerTest.java
  src/test/java/com/yapp/betree/service/UserServiceTest.java
Labels: 💡feature, 👥회원관리, 🔍test

#56 [feat] 메세지 상세 조회 api 및 테스트 추가
  src/main/java/com/yapp/betree/controller/MessageController.java
  src/main/java/com/yapp/betree/dto/response/MessageDetailResponseDto.java
  src/main/java/com/yapp/betree/repository/MessageRepository.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/test/java/com/yapp/betree/controller/MessageControllerTest.java
  src/test/java/com/yapp/betree/repository/MessageRepositoryTest.java
  src/test/java/com/yapp/betree/service/MessageServiceTest.java
Labels: 💡feature, 📬메시지함, 🔍test

#61 feat: 나무 삭제
  src/main/java/com/yapp/betree/controller/ForestController.java
  src/main/java/com/yapp/betree/domain/Message.java
  src/main/java/com/yapp/betree/exception/ErrorCode.java
  src/main/java/com/yapp/betree/repository/MessageRepository.java
  src/main/java/com/yapp/betree/service/FolderService.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/test/java/com/yapp/betree/config/TestConfig.java
  src/test/java/com/yapp/betree/controller/FolderAcceptanceTest.java
  src/test/java/com/yapp/betree/controller/ForestControllerTest.java
  src/test/java/com/yapp/betree/controller/MessageAcceptanceTest.java
  src/test/java/com/yapp/betree/repository/MessageRepositoryTest.java
  src/test/java/com/yapp/betree/service/FolderServiceTest.java
Labels: 💡feature, 🌲칭찬, 📬메시지함

#57 feat: 로그아웃 구현
  src/main/java/com/yapp/betree/controller/OAuthController.java
  src/main/java/com/yapp/betree/exception/ErrorCode.java
  src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
  src/main/java/com/yapp/betree/service/LoginService.java
  src/main/java/com/yapp/betree/service/UserService.java
  src/test/java/com/yapp/betree/config/TestConfig.java
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/controller/ForestControllerTest.java
  src/test/java/com/yapp/betree/controller/MessageControllerTest.java
  src/test/java/com/yapp/betree/controller/OAuthControllerTest.java
  src/test/java/com/yapp/betree/interceptor/TokenInterceptorTest.java
  src/test/java/com/yapp/betree/service/UserServiceTest.java
Labels: 💡feature, 👥회원관리

#63 bug: merge 괄호 누락, 컨트롤러 테스트 쿠키 처리
  src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
  src/main/java/com/yapp/betree/service/UserService.java
  src/test/java/com/yapp/betree/controller/FolderAcceptanceTest.java
  src/test/java/com/yapp/betree/controller/ForestControllerTest.java
  src/test/java/com/yapp/betree/controller/MessageAcceptanceTest.java
  src/test/java/com/yapp/betree/controller/MessageControllerTest.java
  src/test/java/com/yapp/betree/controller/UserAcceptanceTest.java
  src/test/java/com/yapp/betree/controller/UserControllerTest.java
Labels: ⚒bug, 🔍test

#65 bug: withCredentials cors 설정 추가
  src/main/java/com/yapp/betree/config/WebConfig.java
Labels: ⚒bug

#67 bug: 응답으로 보내줄 Authorization 헤더 노출 설정
  src/main/java/com/yapp/betree/config/WebConfig.java
Labels: ⚒bug

#71 bug: 리프레시토큰 쿠키 검증으로 api요청 안되는 오류 임시 해결
  src/main/java/com/yapp/betree/controller/OAuthController.java
  src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
  src/main/java/com/yapp/betree/service/NoticeTreeService.java
  src/main/java/com/yapp/betree/service/oauth/JwtTokenProvider.java
  src/main/resources/application.yml
  src/test/java/com/yapp/betree/controller/OAuthControllerTest.java
Labels: ⚒bug, 👥회원관리

#73 [bug] DB에서 가져온 알림나무 content에 null들어가는 오류 해결
  src/main/java/com/yapp/betree/util/BetreeUtils.java
Labels: ⚒bug, 🌲칭찬

#72 [feat] 서랍메뉴 - 나무 공개 설정
  src/main/java/com/yapp/betree/controller/ForestController.java
  src/main/java/com/yapp/betree/domain/Folder.java
  src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
  src/main/java/com/yapp/betree/service/FolderService.java
  src/test/java/com/yapp/betree/controller/FolderAcceptanceTest.java
  src/test/java/com/yapp/betree/controller/ForestControllerTest.java
  src/test/java/com/yapp/betree/domain/FolderTest.java
  src/test/java/com/yapp/betree/service/FolderServiceTest.java
Labels: 💡feature, 📬메시지함

#78 fix: 5차 스프린트 논의사항 수정
  src/main/java/com/yapp/betree/config/WebConfig.java
  src/main/java/com/yapp/betree/controller/ForestController.java
  src/main/java/com/yapp/betree/domain/Folder.java
  src/main/java/com/yapp/betree/dto/SendUserDto.java
  src/main/java/com/yapp/betree/dto/oauth/OAuthUserInfoDto.java
  src/main/java/com/yapp/betree/dto/response/MessageBoxResponseDto.java
  src/main/java/com/yapp/betree/dto/response/MessageResponseDto.java
  src/main/java/com/yapp/betree/dto/response/UserResponseDto.java
  src/main/java/com/yapp/betree/exception/ErrorCode.java
  src/main/java/com/yapp/betree/repository/MessageRepository.java
  src/main/java/com/yapp/betree/service/FolderService.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/main/java/com/yapp/betree/util/BetreeUtils.java
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/controller/ForestControllerTest.java
  src/test/java/com/yapp/betree/domain/EntityTest.java
  src/test/java/com/yapp/betree/domain/UserTest.java
  src/test/java/com/yapp/betree/repository/MessageRepositoryTest.java
  src/test/java/com/yapp/betree/service/FolderServiceTest.java
  src/test/java/com/yapp/betree/service/JwtTokenTest.java
  src/test/java/com/yapp/betree/service/KakaoApiServiceTest.java
  src/test/java/com/yapp/betree/service/MessageServiceTest.java
  src/test/java/com/yapp/betree/service/UserServiceTest.java
  src/test/java/com/yapp/betree/util/BetreeUtilsTest.java
Labels: ⚒bug, 👥회원관리, 🌲칭찬, 📬메시지함

#79 feat: 회원가입시 비트리 기본메시지 생성 추가
  src/main/java/com/yapp/betree/domain/Message.java
  src/main/java/com/yapp/betree/dto/SendUserDto.java
  src/main/java/com/yapp/betree/service/LoginService.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/main/java/com/yapp/betree/service/UserService.java
  src/main/java/com/yapp/betree/util/BetreeUtils.java
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/service/MessageServiceTest.java
Labels: 💡feature, 👥회원관리, 📬메시지함

#80 test: 실패 테스트 수정
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/repository/MessageRepositoryTest.java
Labels: 🔍test

#81 bug: 이미지 업로드
  src/main/resources/static/image/v1/user_1.png
  src/main/resources/static/image/v1/user_2.png
  src/main/resources/static/image/v1/user_3.png
  src/main/resources/static/image/v1/user_4.png
  src/main/resources/static/image/v1/user_betree.png
  src/main/resources/static/image/v1/user_unknown.png
Labels: ⚒bug

#82 fix: 유저나무숲 응답값에 공개여부 추가
  src/main/java/com/yapp/betree/dto/response/TreeResponseDto.java
  src/test/java/com/yapp/betree/domain/FolderTest.java
Labels: 📬메시지함

#83 bug: 나무 상세 조회시 비공개폴더는 못보도록 예외처리
  src/main/java/com/yapp/betree/controller/ForestController.java
  src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
  src/main/java/com/yapp/betree/service/FolderService.java
  src/test/java/com/yapp/betree/controller/ForestControllerTest.java
  src/test/java/com/yapp/betree/service/FolderServiceTest.java
Labels: ⚒bug, 🌲칭찬

#86 fix: 메시지, 나무 상세조회 버그 수정
  src/main/java/com/yapp/betree/dto/response/MessageDetailResponseDto.java
  src/main/java/com/yapp/betree/service/FolderService.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/main/java/com/yapp/betree/service/UserService.java
Labels: ⚒bug, 💡feature, 📬메시지함

#87 fix: profileImage 두번 처리되는 에러 수정
  src/main/java/com/yapp/betree/dto/response/MessageBoxResponseDto.java
  src/main/java/com/yapp/betree/dto/response/MessageResponseDto.java
Labels: ⚒bug

#88 fix: 삭제된 메시지가 prev,nextId로 조회되지 않도록 수정
  src/main/java/com/yapp/betree/repository/MessageRepository.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/test/java/com/yapp/betree/repository/MessageRepositoryTest.java
Labels: ⚒bug, 📬메시지함

#90 fix: 메세지 읽음 여부 상태 변경 리턴 값 수정
  src/main/java/com/yapp/betree/controller/MessageController.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/controller/MessageAcceptanceTest.java
  src/test/java/com/yapp/betree/controller/MessageControllerTest.java
  src/test/java/com/yapp/betree/service/MessageServiceTest.java
Labels: 🌲칭찬

#91 fix: 알림나무 비어있을 때 처리
  src/main/java/com/yapp/betree/service/NoticeTreeService.java
Labels: ⚒bug

#94 test: 실패 테스트 수정
  src/test/java/com/yapp/betree/controller/FolderAcceptanceTest.java
Labels: 🔍test

#92 fix: 같은 도메인 쿠키설정 추가
  src/main/java/com/yapp/betree/controller/OAuthController.java
  src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
  src/main/java/com/yapp/betree/util/BetreeUtils.java
  src/main/resources/application.yml
  src/main/resources/static/image/v2/user_1.svg
  src/main/resources/static/image/v2/user_2.svg
  src/main/resources/static/image/v2/user_3.svg
  src/main/resources/static/image/v2/user_4.svg
  src/main/resources/static/image/v2/user_betree.svg
  src/main/resources/static/image/v2/user_unknown.svg
  src/test/java/com/yapp/betree/controller/OAuthControllerTest.java
Labels: 👥회원관리, 🔍test

#96 bug: 배포 서버 에러 수정
  src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
  src/main/java/com/yapp/betree/service/MessageService.java
Labels: ⚒bug

#98 feat: 요청 유저 정보 로그출력
  src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
Labels: ⚒bug, ⚙️Infra

#99 feat: 로컬 개발일경우 쿠키 예외처리 - 로그인 유저 이메일로 구분
  .github/workflows/deploy.yml
  src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
  src/main/resources/application.yml
Labels: ⚒bug

#104 fix: 알림나무 갱신 설정 변경, 쿠키설정 변경
  src/main/java/com/yapp/betree/BeTreeApplication.java
  src/main/java/com/yapp/betree/controller/OAuthController.java
  src/main/java/com/yapp/betree/interceptor/TokenInterceptor.java
  src/main/java/com/yapp/betree/service/NoticeTreeService.java
  src/main/java/com/yapp/betree/util/BetreeUtils.java
  src/main/resources/application.yml
  src/test/java/com/yapp/betree/controller/AcceptanceTest.java
  src/test/java/com/yapp/betree/controller/OAuthControllerTest.java
Labels: 💡feature, 🌲칭찬, 🔍test, 🧹refactor

#109 fix: 즐겨찾기 메세지 상세 조회 api 추가 (같은 서비스 로직 사용)
  src/main/java/com/yapp/betree/controller/MessageController.java
  src/main/java/com/yapp/betree/service/MessageService.java
  src/test/java/com/yapp/betree/controller/MessageAcceptanceTest.java
  src/test/java/com/yapp/betree/controller/MessageControllerTest.java
  src/test/java/com/yapp/betree/service/MessageServiceTest.java
Labels: 📬메시지함
